### ISSUE TITLE
Gear guide hands slot page has wrong titles

### ISSUE THREAD

**Issue by Nightfirecat** [Nightfirecat/zulrahguide#14]
Instead of "Hands slot (magic|range) gear", it reads "Shield slot (magic|range) gear"

**Comment by Devil-kushwaha** [comment]
How can I contribute

**Comment by Nightfirecat** [comment]
You can open a pull request. I recommend doing some reading on the topic if you're not familiar: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests

**Comment by Nightfirecat** [comment]
Fixed in #15
